price_min: 100000
price_max: 150000
location: 10
page: 3

# Yerevan -         1
# Ajapnyak -        2
# Arabkir -         3
# Avan -            4
# Davitashen -      5
# Erebuni -         6
# Kanaker-Zeytun -  7
# Kentron -         8
# Malatia-Sebastya- 9
# Nor-Nork -        10
# Shengavit -       11
# Nork Marash -     12
# Nubarashen -      13